### ISSUE TITLE
Content Drip doesn't work with Subscriptions

### ISSUE THREAD

**Issue by danjjohnson** [woothemes/sensei-content-drip#93]
When a course is linked to a Simple Subscription product, lessons on a drip schedule are visible before the lesson has been dripped.

It also seems that if the subscription has a free trial, the drip schedule is reset when the first payment is made (and possibly on every subsequent payment.)

392702-zd-woothemes

**Comment by xqtm** [comment]
what happen is that in the commentmeta table, the entry with meta key="start", related to the comment_post_ID of the entry on the comment table with comment_type="sensei_course_status", changes his value from the date of the beginning of the trial, to the date of the first payment,resetting all the content drip.

this is the query to get the dates that get resetted at first payment. 

SELECT * FROM  wp_users left join  wp_comments on  wp_users.ID= wp_comments.user_id left join  wp_commentmeta on  wp_commentmeta.comment_id =  wp_comments.comment_ID where  wp_commentmeta.meta_key="start"  and wp_comments.comment_post_ID="//////put here the course post id///////" order by wp_commentmeta.meta_value

**Comment by dwainm** [comment]
Fixed as part of the general subscription integration within Sensei core.
